/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"
#include <stdlib.h>
#include <string.h>

void
prog_1(char *host, char * op1, char op, char * op2)
{
	CLIENT *clnt;
	int  *result_1;
	int  *result_2;
	int  *result_3;
	int  *result_4;

	operandos  op_arg;
	op_arg.x = atoi(op1);
	op_arg.y = atoi(op2);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(op) { 
		case '+':
			result_1 = add_1(&op_arg, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			} else {
				printf("Result is %d\n", *result_1);
			}
			break;
		case '-':
			result_2 = sub_1(&op_arg, clnt);
			if (result_2 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			} else {
				printf("Result is %d\n", *result_2);
			}
			break;
		case '*':
			result_3 = mul_1(&op_arg, clnt);
			if (result_3 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			} else {
				printf("Result is %d\n", *result_3);
			}
			break;
		case '/':
			result_4 = div_1(&op_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			} else {
				printf("Result is %d\n", *result_4);
			}
			break;
		default:
			printf("Operador inválido");
			break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char * operando1 = malloc(sizeof(char) * 10);
	char operador = *argv[3];
	char * operando2 = malloc(sizeof(char) * 10);

	strcpy(operando1, argv[2]);
	strcpy(operando2, argv[4]);

	prog_1 (host, operando1, operador, operando2);
exit (0);
}
