/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULA_H_RPCGEN
#define _CALCULA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int x;
	int y;
};
typedef struct operandos operandos;

#define PROG 22222
#define VERSAO 110

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_110(operandos *, CLIENT *);
extern  int * add_110_svc(operandos *, struct svc_req *);
#define sub 2
extern  int * sub_110(operandos *, CLIENT *);
extern  int * sub_110_svc(operandos *, struct svc_req *);
#define mul 3
extern  int * mul_110(operandos *, CLIENT *);
extern  int * mul_110_svc(operandos *, struct svc_req *);
#define div 4
extern  int * div_110(operandos *, CLIENT *);
extern  int * div_110_svc(operandos *, struct svc_req *);
extern int prog_110_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_110();
extern  int * add_110_svc();
#define sub 2
extern  int * sub_110();
extern  int * sub_110_svc();
#define mul 3
extern  int * mul_110();
extern  int * mul_110_svc();
#define div 4
extern  int * div_110();
extern  int * div_110_svc();
extern int prog_110_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULA_H_RPCGEN */
