/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"


void
prog_110(char *host, char * operando_1, char operador, char * operando_2) {
	CLIENT *clnt;
	int  *result;
	operandos  operandos_arg;
	operandos_arg.x = atoi(operando_1);
	operandos_arg.y = atoi(operando_2);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operador) {
		case '+':
			result = add_110(&operandos_arg, clnt);
			break;
		case '-':
			result = sub_110(&operandos_arg, clnt);
			break;
		case '*':
			result = mul_110(&operandos_arg, clnt);
			break;
		case '/':
			result = div_110(&operandos_arg, clnt);
			break;
		default:
			printf("Invalid operator");
	}

	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Result is %d\n", *result);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];

	char * operando1 = malloc(sizeof(int));
	char operador = *argv[3];
	char * operando2 = malloc(sizeof(int));

	strcpy(operando1, argv[2]);
	strcpy(operando2, argv[4]);

	if(atoi(operando1) == 0 || atoi(operando2) == 0) {
		printf("Operandos devem ser maiores que 0\n");
		return 0;
	}

	prog_110 (host, operando1, operador, operando2);

exit (0);
}
