/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *
add_110_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x + argp->y;

	return &result;
}

int *
sub_110_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x - argp->y;

	return &result;
}

int *
mul_110_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x * argp->y;

	return &result;
}

int *
div_110_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x / argp->y;

	return &result;
}
