/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"
#include <stdlib.h>
#include <string.h>

void
prog_100(char *host, char * operando_1, char operador, char * operando_2)
{
	CLIENT *clnt;
	int  *result;

	operandos  operandos_arg;
	operandos_arg.x = atoi(operando_1);
	operandos_arg.y = atoi(operando_2);

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operador) {
		case '+':
			result = add_100(&operandos_arg, clnt);
			break;
		case '-':
			result = sub_100(&operandos_arg, clnt);
			break;
		default:
			printf("Operador inválido\n");
	}

	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Result is %d\n", *result);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	char * operando_1 = malloc(sizeof(int));
	char operador = *argv[3];
	char * operando_2 = malloc(sizeof(int));

	strcpy(operando_1, argv[2]);
	strcpy(operando_2, argv[4]);

	prog_100 (host, operando_1, operador, operando_2);
exit (0);
}
